### PR TITLE
Add Release Notes for iOS Release 1.58.2

### LINKED ISSUE #8543: Release Notes for iOS Release 1.58.2
### 1.58.2

- Fixed crash when loading https://dailmaily.co.uk. ([#8346](https://github.com/brave/brave-ios/issues/8346))
- Fixed playlist not working with high quality videos on https://youtube.com. ([#8350](https://github.com/brave/brave-ios/issues/8350))

### PR DESCRIPTION
**Pull request by Uni-verse**
## Summary of Changes

This pull request fixes [#8543](https://github.com/brave/brave-ios/issues/8543)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kjozwiak — APPROVED** [review]
LGTM 👍

**Comment by kjozwiak** [comment]
Might need review from @iccub as I can't merge due to the tests being skipped/not passing via https://github.com/brave/brave-ios/actions/runs/7170225164/job/19544535440?pr=8544. Tried re-running several times but the job just keeps getting skipped.

**Review by iccub — APPROVED** [review]
Done :)

**Comment by Uni-verse** [comment]
Thanks for the reviews guys.

**Pull request merged**
