### PR TITLE
fix error color to red

### PR DESCRIPTION
**Pull request by izabekz**
## Summary of Changes

This pull request fixes issue #1818 

## Submitter Checklist:

- [checked] *Unit Tests* are updated to cover new or changed functionality
- [checked] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — COMMENTED** [review]
Thanks, can you add a screenshot on how the pin screen looks after the fix?

**Comment by jhreis** [comment]
In this case, for both iOS 13 and iOS 12 would be nice (for screenshots). Can use the simulator. If you are unable to do this, just let us know.

**Comment by izabekz** [comment]
@iccub @jhreis will add as soon as i will solve error when building, tomorrow after work, sorry for inconvenience

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/1975, thanks for your contribution anyway :)

**Pull request closed without merging**
