### PR TITLE
Fix #63: Adds the User Referral Program

### LINKED ISSUE #63: User Referral Promo (URP) Integration
Convert existing URP functionality. User Referral Promo is used to anonymously track referral codes from specific sources and retention metrics for a maximum of 90 days.

- [ ] Move necessary files
    - See the [URP directory](https://github.com/iccub/browser-ios/tree/development/brave/src/analytics/user-referral-program), 5 files currently.
- [ ] Update preference locations for saved data [_maybe_] (see https://github.com/brave/brave-ios/pull/61#issuecomment-402520054)
- [ ] Connect any necessary function calls (calling into the URP files from AppDelegate, or where ever)
    - `startApplication` on AppDelegate is main contact point 
- [ ] URP authenticates against certificate authority, so must move necessary certs as well as coding in the checks (note, this is not cert pinning, just authority check). See https://github.com/brave/browser-ios/commit/506509f64f20ed89c15f97f8e79ee1f2eae98c46
- [ ] Unit Tests

Please note: this does _not_ include [DAU integration](https://github.com/brave/browser-ios/blob/development/brave/src/analytics/DAU.swift#L89).

Related:
https://github.com/brave/brave-ios/issues/189

### PR DESCRIPTION
**Pull request by kylehickinson**
## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_None included_

## Notes for testing this patch

I assume to test this properly you need an API key and access to the data?

### CODE REVIEW

**Comment by kylehickinson** [comment]
Just to note, 1.6 didn't have unit tests but I'm not sure how we would unit test this specifically. I don't have full clarity of the feature itself, so if someone could give me some info on that on what needs to be tested specifically I can write some unit tests as well :)

**Review by jhreis — CHANGES_REQUESTED** [review]
There is a small change I think that will be made on this in 1.6, so want to block this for right now. Sorry for the inconvenience :/

**Comment by kylehickinson** [comment]
No worries, just let me know whenever things are ready :)

**Comment by jhreis** [comment]
This can now be updated. We just merged https://github.com/brave/browser-ios/pull/1778#pullrequestreview-168483289 into browser-ios.

Probably easiest to just completely re-copy the entire file to be safe.

**Comment by kylehickinson** [comment]
Pushed as a separate commit for clarity but can be squashed on merge.

Note: We don't have any scripting that updates the info.plist with the API keys at the moment (I assume this will be done with #108?)

**Comment by jhreis** [comment]
We should file a separate ticket for that I think, just to make sure it is tracked and implemented. We may not fully automate beta builds for a bit.

**Review by jhreis — APPROVED** [review]

**Pull request merged**
