### PR TITLE
Fix #867: Status bar changes its position in horizontal mode on setti…

### LINKED ISSUE #867: Status bar changes its position in horizontal mode on settings screen.
### Steps to Reproduce 
  1. Open settings
  2. Flip phone to landscape

**Actual result:** 
zrzut ekranu 2019-02-6 o 18 59 59

**Expected result:**
Should stay in portrait mode

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by boska**
## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

This is for iPhones only.
1. Open settings
2. Verify that status bar is showing correctly in landscape mode.

### Screenshots:

simulator screen shot - iphone 7 - 2019-02-20 at 15 40 49

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable)

### CODE REVIEW

**Comment by iccub** [comment]
Hey, do you plan to add more to this PR? I see you posted it as a draft

**Comment by boska** [comment]
Hi, I'm not sure about this. If so I just set this PR to "ready to review" ?

**Comment by iccub** [comment]
Yes, please do. Draft pull requests are for work in progress work, when your code is unfinished yet and not ready for review.

**Review by iccub — APPROVED** [review]
Sorry for having to wait so long, the PR looks nice, Thanks for your first contribution to our repo :)

**Pull request merged**
