### PR TITLE
Fix #1962: Change scheme names

### LINKED ISSUE #1962: Update Scheme Names in Xcode
### Description: 

Update Xcode scheme names to be better. They are not tremendous. 

### Steps to Reproduce 
  1. Open project
  2. See Schemes

**Actual result:** 

Xcode Scheme Names

**Expected result:**

`Fennec` → `Debug`
`Fennec_Enterprise` → `Dev`
`Firefox_Beta` → `Beta`
`Firefox` → `Release`

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

100%

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by iccub**
Fix #1962 

## Summary of Changes

Schemes are changed as follows
`Fennec` -> `Debug`
`Fennec_Enterprise` -> `Dev`
`Firefox_Beta` -> `Beta`
`Firefox` -> `Release`

Unused UITests schemes got removed

It's not easy to give a review by just looking at project file changes so the overall summary of steps:
1. Renaming scheme via manage schemes option
2. Renaming build configurations(`Client` project -> `Configurations`)
3. Renaming xconfig files to match
4. Changing build configurations for remaining targets: Share extension, Shared, Data...

There are still places that could be updated like `FENNEC_..` flag names, but I decided to not put too much changes in this PR, can be done later

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Zrzut ekranu 2019-11-14 o 13 09 40

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by kylehickinson** [comment]
Do we have any plans to change these: 
image

**Comment by iccub** [comment]
I left them for later but can change it if you think it fits scope of this PR

**Comment by kylehickinson** [comment]
No that's fine we can take this one step at a time, was just wondering 🙂

**Comment by jhreis** [comment]
@iccub Sorry this is so stale, if you update from dev, ping me and I will review ASAP to get this merged in.

**Comment by jhreis** [comment]
Removed block label, since nothing to prevent it being merged.

**Review by jhreis — APPROVED** [review]

**Pull request merged**
