### PR TITLE
Fix #7882: Enable cookie consent notice blocking by default

### LINKED ISSUE #7882: Enable cookie consent notice blocking by default
### Description: 
We want to now enable this by default

### Steps to Reproduce 
  1. Install the app from scratch
  2. Check that cookie consent notice blocking is enabled
  3. Test cookie consent notice blocking works (will need to wait a few minutes as the necessary files download)

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #7882

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

See issue for STR

Also note for QA : Please check Cookie Consent Popover is not presented

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by soner-yuksel** [comment]
Please add the issue to description under `This pull request fixes #7882`
Fix the title of the PR by including `Fix #7882: Enable cookie consent notice blocking by default`

And Please FIX the tests, CI is giving error and saying cookieconsent doesnt exist anymore in Tests!

**Review by soner-yuksel — CHANGES_REQUESTED** [review]
Please remove the `GIFImage`, it is not used anymore and we should not use in future. (Don't accept GIF from designer to be displayed somewhere in the app)

**Comment by cuba** [comment]
> Please remove the `GIFImage`, it is not used anymore and we should not use in future. (Don't accept GIF from designer to be displayed somewhere in the app)

Right forgot about this file. Thanks for the reminder

**Comment by cuba** [comment]
> Please add the issue to description under `This pull request fixes #7882` Fix the title of the PR by including `Fix #7882: Enable cookie consent notice blocking by default`
> 

Done

> And Please FIX the tests, CI is giving error and saying cookieconsent doesnt exist anymore in Tests!

Ahh sorry did this late last night and didn't want to scrap my brave-core changes so I did it in the dark.

**Review by soner-yuksel — APPROVED** [review]

**Pull request merged**
