### PR TITLE
Fix #109: Only show green lock for fully secure sites

### LINKED ISSUE #109: Certificate Errors Show Green Lock

### PR DESCRIPTION
**Pull request by cndouglas**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have marked the bug with `[needsuplift]`
- [x] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

Fully secure HTTPS site (behavior unchanged) https://badssl.com/

HTTPS site with certificate error (green lock is now hidden) https://expired.badssl.com/

HTTPS site with mixed content (green lock is now hidden) https://www.bennish.net/mixed-content.html

HTTP unsecure site (behavior unchanged) http://neverssl.com/

## Notes for testing this patch

Previously, all sites with URLs that begin with `https` had the green lock icon in the url bar. This change hides the green lock when browsing sites with certificate errors or mixed content.

Note that sites with certificate errors or mixed content are now treated the same as unsecure HTTP sites. This matches iOS Safari's behavior.

QA Steps:

1. Create a new tab and navigate to https://badssl.com/. The green lock should be visible.
2. Tap the "expired" link, which goes to https://expired.badssl.com/. The green lock should be hidden.
3. Create a new tab and navigate to https://www.bennish.net/mixed-content.html. The green lock should be hidden.
4. Create a new tab and navigate to http://neverssl.com/. The green lock should be hidden.

### CODE REVIEW

**Review by jhreis — APPROVED** [review]
I am approving this from a coding perspective. @tmancey can you please do a quick security pass on this?

**Review by tmancey — APPROVED** [review]

**Review by tmancey — CHANGES_REQUESTED** [review]
Discussing with security team

**Comment by tmancey** [comment]
@jhreis From a security perspective this is a great improvement and a must have, but ideally we should be following Brave desktop as follows, your thoughts on whether we merge this PR and create an enhancement ticket for those changes?

Secure connection:

secure connection

Partially secure connection:

partially insecure connection

Insecure connection:

insecure connection

**Comment by srirambv** [comment]
@tmancey expected to not show page load time for insecure connection?

**Comment by jhreis** [comment]
I think we'll need to build off of this, but does seem to provide additional improvements from what we currently have. @tmancey feel free to re-review and merge.

**Review by tmancey — APPROVED** [review]
Approved

**Comment by tmancey** [comment]
@srirambv I am not sure of the business requirement for page load time, however these screenshot snippets were taken from latest live Desktop browser

**Pull request merged**
