### PR TITLE
Fix #1524: Deprecated UIWebView in 1Password extension.

### LINKED ISSUE #1524: 1Password extension uses deprecated UIWebView
See issue https://github.com/agilebits/onepassword-app-extension/issues/409

This makes our app to show deprecation notice too.

To temporarily fix this we can either use open PR which fixes it https://github.com/agilebits/onepassword-app-extension/pull/411

or fork this PR to my own repo if there are any security concerns with pointing to an open PR
For carthage we use pinned framework versions

@jumde is it okay to use that PRs branch until it's merged into upstream? Deadlines are tight so we need some temp solution for this

### PR DESCRIPTION
**Pull request by iccub**
We will go back to old branch once this is merged, ref #1527

## Summary of Changes

This pull request fixes issue #1524 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by danishjafri88 — APPROVED** [review]

**Comment by Sidetalker** [comment]
I am truly honored 🤓

**Comment by iccub** [comment]
@Sidetalker I just tipped you 5 BAT via github, thanks for your indirect contribution to brave-ios :D

**Comment by Sidetalker** [comment]
Thanks @iccub!

**Comment by Sidetalker** [comment]
Hey @iccub, your tip encouraged me to try out Brave and I'm loving it. A bit embarrassed to say I haven't been able to figure out how to claim the 5 BAT you tipped - could you point me in the right direction? Regardless, Brave has become my primary browser on both mobile and desktop!

I've signed up as a creator, verified my Uphold account, and have added Github as a channel - but it displays 0.00 BAT.

**Comment by iccub** [comment]
@Sidetalker seems like the previous donation as a unverified github publisher didn't work, I sent you some more BAT, please check again in some time :)

Zrzut ekranu 2019-09-29 o 16 18 19

**Comment by Sidetalker** [comment]
Perfect, that worked - thanks @iccub!

**Pull request merged**
