### PR TITLE
Fix #8556: Add GPC toggle

### LINKED ISSUE #8556: add GPC for iOS
for parity with https://github.com/brave/brave-browser/issues/32231

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes

This pull request fixes #8556 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Test using console (navigator.globalPrivacyControl should return the appropriate value)

Note: There is no support for the header value yet

## Screenshots:

Simulator Screenshot - iPhone 14 - 2024-01-04 at 12 34 34

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — CHANGES_REQUESTED** [review]
Fix build errors. Rest looks good to me

**Comment by ShivanKaul** [comment]
@cuba can you add screenshots?

**Review by iccub — APPROVED** [review]

**Comment by cuba** [comment]
> @cuba can you add screenshots?

Uploaded

**Comment by diracdeltas** [comment]
cc @Brave-Matt could you update our privacy user support document to mention this? something like `On iOS, GPC is only enabled via the JavaScript API for now, which can be disabled in Settings under Brave Shields and Privacy.`

**Pull request merged**
