### PR TITLE
Ref #1925: Use push action for CI

### PR DESCRIPTION
**Pull request by iccub**
Without it, the cache isn't saving, making all new pull requests to run a clean build.

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by kylehickinson — APPROVED** [review]
Im fine with this, anyone else (@jhreis @Brandon-T) have any reason to keep `pull_request` (making 2 builds per PR)? This change means it will only build the branch itself (i.e. `nobug/gh_actions_push`) and not the post-_merged_ branch.

**Comment by iccub** [comment]
It will run 'post merge', after the PR is merged, you are able to see status on the destination branch from commit list

**Comment by kylehickinson** [comment]
Yep, it will because development is technically pushed then :) But at that point it may be too late 😅

**Comment by Brandon-T** [comment]
So instead of making two builds for a single PR, it builds the branch just once on a per-push basis?
If true, I'm good with that. Will just have to make sure not to push a million commits which might actually lead to cleaner history too.

**Review by Brandon-T — APPROVED** [review]

**Comment by kylehickinson** [comment]
Right, it will build once as if you were checked out into that given branch. Meaning it will also compile development when a PR merges

**Pull request merged**
