### PR TITLE
Add Release Notes for iOS Release 1.58.1

### LINKED ISSUE #8527: Release Notes for iOS Release 1.58.1
### 1.58.1

- Fixed Adblock initialization crash. ([#8334](https://github.com/brave/brave-ios/issues/8334))

### PR DESCRIPTION
**Pull request by Uni-verse**
## Summary of Changes

This pull request fixes [#8527](https://github.com/brave/brave-ios/issues/8527)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by Uni-verse** [comment]
Hi @iccub we will need to create a tag for this release. Thank you.

**Review by kjozwiak — APPROVED** [review]
LGTM 👍

**Review by soner-yuksel — APPROVED** [review]

**Review by iccub — APPROVED** [review]

**Comment by Uni-verse** [comment]
@iccub @soner-yuksel Appreciate the reviews gentlemen. Ok to bypass ruleset requirements?

**Comment by kjozwiak** [comment]
> @iccub @soner-yuksel Appreciate the reviews gentlemen. Ok to bypass ruleset requirements?

Should be fine as the above is basically just updating the `CHANGELOG` and doesn't touch any code. Merging.

**Pull request merged**
