### PR TITLE
Fixes #4896: Force to portrait mode 

### LINKED ISSUE #4896: Opening Brave Wallet from landscape orientation doesn't force portrait
### Description: 

If you open Brave Wallet while you're in landscape it can get into some weird states

### Steps to Reproduce 
  1. Rotate to landscape
  2. Open the menu
  3. Open Brave Wallet

**Actual result:**

Brave Wallet presents in landscape despite only supporting portrait mode. Also further rotation can cause some strange bugs:

IMG_5130

**Expected result:**

Should force into portrait mode and not bug out while rotating

**Reproduces how often:** Always

### PR DESCRIPTION
**Pull request by VaishaliDesai**
Thank you for letting me contribute to the brave-iOS code base.

## Summary of Changes

This pull request fixes #4896 

This PR add force to brave wallet to open in portrait mode if the device is iPhone and in landscape mode 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

Before the changes, brave wallet in landscape mode

After the changes, brave wallet in landscape mode

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by kylehickinson** [comment]
Thanks @VaishaliDesai !! I will check this out today :)

**Review by kylehickinson — CHANGES_REQUESTED** [review]
Looks like there's a small bug after it moves the screen to portrait mode, the graphs header seems to stay its landscape size and gets cut off.  It may be a SwiftUI bug in particular, perhaps the `WalletHostingViewController` needs a relayout after switching to portrait

image

**Comment by VaishaliDesai** [comment]
> Looks like there's a small bug after it moves the screen to portrait mode, the graphs header seems to stay its landscape size and gets cut off. It may be a SwiftUI bug in particular, perhaps the `WalletHostingViewController` needs a relayout after switching to portrait

Thanks for testing this at your end. This definitely seems an issue however I can't seem to reproduce it on simulator iPhone 13 iOS 15.2. Would you mind which OS and device did you use for this so I can try? 

Edit - I have set the property shouldAutorotate to `true` to check if it fixes the problem you are seeing with the orientation
change.

**Comment by kylehickinson** [comment]
@VaishaliDesai Ah, perhaps this is a bug in 15.0 then, we're still using Xcode 13.1 here due to some bugs with 13.2 and up, I will double check the new solution with both on Monday :) thanks again!

**Comment by VaishaliDesai** [comment]
Thank you @kylehickinson

**Comment by VaishaliDesai** [comment]
Hi @kylehickinson, does the new change seem to fix the issue?

**Comment by kylehickinson** [comment]
Hey @VaishaliDesai, sorry unfortunately haven't had a chance to take a look at the new changes yet. I will have someone else maybe take a look if I can't get to it myself soon, thanks!

**Review by iccub — APPROVED** [review]
I checked on both iOS 15.0 and 15.2, works great :)
Thank you for contributing to Brave

@kylehickinson can you hit approve on your review?

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Thanks for picking this up @iccub :)

**Comment by VaishaliDesai** [comment]
Thank you both @iccub and @kylehickinson to help verify this change.

**Pull request merged**
