### PR TITLE
Fix #1849: Updated DAU release pings to use 'release' instead of 'stable'.

### LINKED ISSUE #1849: Update DAU Channel from `stable` to `release`
### Description: 
Currently mobile platforms use `channel=stable` and we should update this to be `channel=release`

There are two changes required:

1. AppConstants.swift
`serverChannelParam`:
```
case .release:
     return "stable"
```
Change to `return "release"`

<br>

2. DAUTests.swift
`let releaseExpected = URLQueryItem(name: "channel", value: "stable")`
Needs to be updated to:
`let releaseExpected = URLQueryItem(name: "channel", value: "release")`

### Testing

No QA is probably needed for this, but a simulation on an app store binary should be run and verified with backend team.

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This pull request fixes issue #1849

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

*No test plan for QA*

Should upload production binary (with API key), and hit server. Have backend team validate iOS has submitted a `channel=release` ping successfully and it is being counted.

## Screenshots:

NA

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by jhreis** [comment]
Some of these changes are dependent on https://github.com/brave/brave-ios/pull/1847. So this PR will be massively simplified once that is updated.

**Comment by kylehickinson** [comment]
Please rebase :)

**Review by iccub — CHANGES_REQUESTED** [review]
Need a rebase or fresh PR,  too many change here

**Comment by iccub** [comment]
Closing, will get fixed here https://github.com/brave/brave-ios/pull/2020

**Pull request closed without merging**
