### PR TITLE
Fix #2447: Removed unnecessary shared schemes.

### LINKED ISSUE #2447: Remove Unnecessary Shared Schemes
### Description: 

Currently Xcode is syncing a bunch of schemes, most of these can be removed. Reduce down to just the main four targets:

- Debug
- Dev
- Beta
- Release

A list of a bunch of Xcode shared schemes

### PR DESCRIPTION
**Pull request by jhreis**
## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by jhreis** [comment]
re-added the release shared scheme.

**Review by kylehickinson — COMMENTED** [review]
What about the schemes:
- BraveShared
- Today
- BraveShareTo
- sqlcipher
- Data
- BraveRewardsUI
- BraveUI

I don't know that they're necessary to be shared. CI only needs the main 4

**Comment by jhreis** [comment]
@kylehickinson I never build those manually, but if others do, we may as well share them.

**Comment by kylehickinson** [comment]
As far as I know, no one builds any non-app scheme manually and even if they did they can auto-generate them. Shared schemes are pretty much just for CI

**Comment by iccub** [comment]
@jhreis dear contributor, any updates on this? 🤡

**Comment by iccub** [comment]
Fixed in https://github.com/brave/brave-ios/pull/2862

**Pull request closed without merging**
