### PR TITLE
[WIP] Fix #309: Add color attribute to Domain model.

### LINKED ISSUE #309: Core data parity between 1.6 and 1.7
The goal is to have the same database schema on both versions. It will help with upgrading to the new codebase.

### PR DESCRIPTION
**Pull request by iccub**
## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Comment by iccub** [comment]
Note: I had to remove some of business logic regarding favicon fallback color, we need to update it anyway. I made a ticket for it here https://github.com/brave/brave-ios/issues/311

**Review by jhreis — CHANGES_REQUESTED** [review]
Let's wait on merging this until `Model8` is finalized on `browser-ios` from the sync ordering changes.  Blocking release for now, and will re-review once we copy the new model over.

**Comment by iccub** [comment]
Note: if we want to wait until `sync-reordering` branch lands on 1.6, we will need to add `syncOrder` attribute to `Bookmark`.

**Comment by jhreis** [comment]
@iccub Is this needed anymore?

**Comment by iccub** [comment]
Since we decided to go with firefoxes implementation of fallback favicons, no. Closing

**Pull request closed without merging**
