### PR TITLE
Fix #58: New tab should not be allowed to add as a bookmark

### LINKED ISSUE #58: New tab should not be allowed to add as a bookmark
image

### PR DESCRIPTION
**Pull request by tmancey**
*Thank you for submitting a pull request, your contributions are greatly appreciated!*

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
## Pull Request Checklist

- [x] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have marked the bug with `[needsuplift]`
- [x] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

### CODE REVIEW

**Review by kylehickinson — DISMISSED** [review]
Looks good, just a minor nit pick: `!url.isAboutHomeURL` rather than `== false`

**Comment by jhreis** [comment]
I think we want to make the solution here more general. We should probably block all `localhost` URLs from being bookmarkable, not just the home page.

**Comment by tmancey** [comment]
@jhreis Agreed, I was going to raise another ticket for this work to make sure that QA do not miss the change based upon the issue title, or would you prefer to be completed under this issue?

**Comment by tmancey** [comment]
Changed to use ```url.isLocalUtility``` so that all URL utilities are ignored: ```"/errors"```, ```"/about/sessionrestore"```, ```"/about/home"``` and ```"/reader-mode"```

**Comment by kylehickinson** [comment]
Why not use `isLocal` instead of `isLocalUtility` if we want to block all `localhost` URLs from being added?

**Comment by tmancey** [comment]
@kylehickinson Using ```isLocal``` blocks all localhost, i.e. if I start Apache on macOS using ```sudo apachectl start``` and then visit http://localhost I cannot add as a bookmark, using ```isLocalUtility``` only blocks Brave browser localhost usage.

Remember to stop Apache after with ```sudo apachectl stop```

@jhreis Based upon your previous comment "We should probably block all localhost URLs from being bookmarkable, not just the home page.", I would assume you did not want to block users from navigating to their own localhost?

**Comment by kylehickinson** [comment]
> if I start Apache on macOS using sudo apachectl start and then visit http://localhost I cannot add as a bookmark, using isLocalUtility only blocks Brave browser localhost usage.

I guess thats a problem for simulator, but if you were to do that on device you wouldn't be connecting to your mac via localhost, you'd be doing so via its local IP address.

**Comment by tmancey** [comment]
> I guess thats a problem for simulator, but if you were to do that on device you wouldn't be connecting to your mac via localhost, you'd be doing so via its local IP address.

Very true :-) There is a reason to stop using simulators 👍

**Review by kylehickinson — APPROVED** [review]

**Review by jhreis — APPROVED** [review]
Sorry for missing part of the below discussions. Looks great though. Thanks 😄 

QA doesn't look at code diffs, just behavior, so making this a more general solution for a specific bug (e.g. about page), is completely fine/correct!

**Pull request merged**
