### PR TITLE
Fix #1708: Update Rewards Panel Icon to have more contrast in dark mode

### LINKED ISSUE #1708: Verified publisher on dark theme needs more contrast
### Description: 
Verified publisher on dark theme needs more contrast

**Actual result:** 
Looks more blurred and blended in the dark mode on device. Screenshot doesn't do justice 
image
on iPad
image

**Expected result:**
Have a more prominent contrast for the verified icon on dark theme

**Reproduces how often:** [Easily reproduced, Intermittent Issue]
Easy

**Brave Version:** 
1.13

**Device details:** 
Both iPhone and iPad

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)? 

### Additional Information
cc: @jamesmudgett @jenn-rhim

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #1708 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Enable Rewards
- Go into dark mode
- Visit a verified publisher, icon should be easier to see (white checkmark)

## Screenshots:

Simulator Screen Shot - iPhone 11 Pro - 2019-10-17 at 14 43 19

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by iccub** [comment]
Does it look good in light mode on iOS 12 too?

**Comment by kylehickinson** [comment]
Yep!

Simulator Screen Shot - iPhone Xs - 2019-10-17 at 15 32 10

**Comment by Brandon-T** [comment]
Hmm.. I was looking for the code where this gets dynamically updated when you switch modes but couldn't find it.

**Comment by kylehickinson** [comment]
@Brandon-T It doesn't get updated based on light/dark mode. We are just using the one that has a white checkmark regardless

**Review by Brandon-T — APPROVED** [review]

**Pull request merged**
