### PR TITLE
Fix #428: Use `WKPreferences.javascriptEnabled` for script blocking

### LINKED ISSUE #428: Migrate Script Blocking to use `javaScriptEnabled`
Currently Javascript is blocked via content rules. `webView.configuration.preferences` contains a `javaScriptEnabled` flag that should be utilized. 

Shield enabling should be detectable via: `!domainForShields.shieldIsEnabled(.NoScript)` inside of:
```
webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy)
```

This also requires changes to stats collection, as stats currently leverage all content rules for detection.

### PR DESCRIPTION
**Pull request by kylehickinson**
## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

simulator screen shot - iphone 8 - 2018-11-22 at 12 03 02

### CODE REVIEW

**Comment by cndouglas** [comment]
Also fixes #429.

**Review by jhreis — CHANGES_REQUESTED** [review]
Given that script blocking is no longer a content rule, we should also:
- remove the rule file `block-scripts.json`
- delete the `script` entry in the `BlocklistName` enum
- update stats to no longer reference `BlocklistName.script`

Preferably we'd also abstract:

```
func include(domainSetting domain: NSNumber?, globalValue global: Preferences.Option<Bool>) -> Bool {
            return domain == 1 || (domain == nil && global.value)
        }
```

(and redo with your better logic), and use this. Not sure where to abstract this to, maybe `Domain`?

One probably better approach would be to just pass in a rule `BraveShieldState.Shield` value:
`someDomain.isOn(shield: BraveShieldState.Shield.NoScript)`

And then internalize all of the logic there (fetching both the global preference (`Preferences.Shields.blockScripts.value`) and the correct property off of the `Domain` (`domainForShields.shield_noScript?.boolValue`)

**Comment by kylehickinson** [comment]
One of the reasons I kept the CB in for the time being is: if I remove it, the stats collecting gets a bit funky (since script won't be a blocklist anymore)

As for the Domain shortcut… The shields preferences are actually in the `Client` so `Data` can't get it 😅. I'll figure out another spot for it though.

**Comment by kylehickinson** [comment]
PR conflicts with #433 (`TPPageStats` change). Either will need rebase after the other's merge

**Review by jhreis — APPROVED** [review]
This is really solid, super nice work!

**Pull request merged**
