### PR TITLE
Ref #5156: Enable fingerprint protection by default

### PR DESCRIPTION
**Pull request by cuba**
## Summary of Changes
Enable fingerprint protection by default

This is a missing part to #5156. No additional ticket created.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

Just go to a new website and make sure that FP is enabled

## Screenshots:

Simulator Screen Shot - iPhone 12 Pro - 2022-05-04 at 10 16 35

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Comment by kylehickinson** [comment]
Can you add the test case in this PR to the test case in the original farbling issue?

**Review by kylehickinson — APPROVED** [review]

**Comment by kylehickinson** [comment]
Also does this need to go out with 1.38/Farbling release?

**Comment by cuba** [comment]
I think ideally yes. @pes10k what do you think?

**Comment by pes10k** [comment]
I think so if at all possible

**Comment by cuba** [comment]
> Also does this need to go out with 1.38/Farbling release?

Is there something I should do to make this go into 1.38? Like make another PR to another branch or rebase this onto another branch?

**Comment by kylehickinson** [comment]
We will merge to dev first then cherry pick to `release` branch and make new builds for QA

**Review by Brandon-T — APPROVED** [review]

**Pull request merged**
