### PR TITLE
Fix #1683: Update verified/unverified publisher icons

### LINKED ISSUE #1683: Update Pub verified/unverified indicators
Rewards is using the old pub verified status icons. New ones attached.
[Archive.zip](https://github.com/brave/brave-ios/files/3729903/Archive.zip)

### PR DESCRIPTION
**Pull request by kylehickinson**
## Summary of Changes

This pull request fixes issue #1683 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Enable rewards
- Visit a unverified publisher, verify round grey icon
- Visit a verified publisher (i.e. bumpsmack.com), verify rounded icon in both panel + URL bar

## Screenshots:

| Unverified | Verified |
| --- | --- |
| Simulator Screen Shot - iPhone 11 Pro - 2019-10-15 at 15 30 20 | Simulator Screen Shot - iPhone 11 Pro - 2019-10-15 at 15 30 09 |

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by Brandon-T — APPROVED** [review]

**Comment by Brandon-T** [comment]
For the publisher icon (IE: The "reddit" icon in the OP), is it supposed to have a circle around it?

**Comment by kylehickinson** [comment]
Not sure what you mean by "have a circle around it".

**Comment by Brandon-T** [comment]
@kylehickinson 

iOS:
Screen Shot 2019-10-15 at 4 19 34 PM

Android:
Screen Shot 2019-10-15 at 4 19 28 PM

**Comment by kylehickinson** [comment]
Ahh, yes it is supposed to be circled, based on designs I made the UI from. Not sure why Android's isn't

**Pull request merged**
