### PR TITLE
Fix #3044: Search Suggestion Text Color blinks when text is entered

### LINKED ISSUE #3044: Search suggestion text color blinks when text is entered
### Steps to Reproduce 
  1. Enable search suggestion
  2. Start typing something

**Actual result:** 
Text color blinks

**Expected result:**

**Reproduces how often:** [Easily reproduced, Intermittent Issue]

**Brave Version:** 

**Device details:** 

**Website problems only:**
- did you check with Brave Shields down?
- did you check in Safari/Firefox (WkWebView-based browsers)?

### PR DESCRIPTION
**Pull request by soner-yuksel**
This PR fixes Search suggestion Text Color flickering. Re-organization will be another PR.

## Summary of Changes

This pull request fixes #3044

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Load Brave Browser
- Go Settings - Search Engines - Enable Search Suggestions
- Create a new Tab and load a Webpage and press search bar
- Start typing something
- Observe Search Suggestion Boxes Text color is not flickering from blue to white

## Screenshots:

ezgif-7-f5203d6961b3

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

### CODE REVIEW

**Review by iccub — CHANGES_REQUESTED** [review]
Code looks good overall, I found one artifact though, happens on iOS 12, see top left in the search suggestions view, there's something blue there

Zrzut ekranu 2020-11-30 o 15 07 21

**Comment by soner-yuksel** [comment]
> Code looks good overall, I found one artifact though, happens on iOS 12, see top left in the search suggestions view, there's something blue there
> 

Yeah what is that artifact let me check why it might happen.

**Comment by soner-yuksel** [comment]
> Code looks good overall, I found one artifact though, happens on iOS 12, see top left in the search suggestions view, there's something blue there
> 

iOS 12 Search Icon Artifact Problem is fixed.

**Review by iccub — APPROVED** [review]
Looks good, tested on iOS 14 and 12

**Review by iccub — APPROVED** [review]

**Review by iccub — APPROVED** [review]

**Pull request merged**
